version: '3.8'

services:
  ac-worldserver-blizz-ptr:
    stdin_open: true
    tty: true
    image: azerothcore/worldserver-blizz-ptr
    container_name: ac-worldserver-blizz-ptr
    restart: unless-stopped
    privileged: true
    build:
      context: ${WORLDSERVER_BUILD_CONTEXT:-./docker/worldserver}
      dockerfile: Dockerfile
    networks:
      - ac-network
    ports:
      - ${WORLD_EXTERNAL_PORT:-8085}:8085
    volumes:
      - type: bind
        source: ${WORLDSERVER_BIN:-./docker/worldserver/bin}
        target: /azeroth-server/bin
      - type: bind
        source: ${WORLDSERVER_ETC:-./docker/worldserver/etc}
        target: /azeroth-server/etc
      - type: bind
        source: ${WORLDSERVER_LOGS:-./docker/worldserver/logs}
        target: /azeroth-server/logs
      - type: bind
        source: ${WORLDSERVER_DATA:-./docker/worldserver/data}
        target: /azeroth-server/data

networks:
  ac-network:
    external:
      name: ac-network
