version: '3.8'

services:
  ac-database:
    image: azerothcore/database
    container_name: ac-database
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/database/Dockerfile
    networks:
      - ac-network
    ports:
      - ${DB_EXTERNAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql

volumes:
  ac-database:
    name: ac-database

networks:
  ac-network:
    name: ac-network
